//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientServiceDocument
    {
        public int IdClientServiceDocument { get; set; }
        public int IdClentService { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ClientService ClientService { get; set; }
    }
}
