//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class InnerCategory
    {
        public int IdInnerCategory { get; set; }
        public int MainCategory { get; set; }
        public int AddCategory { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ProductCategory ProductCategory1 { get; set; }
    }
}
