//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOnWareHouse
    {
        public int IdProdOnWareHouse { get; set; }
        public int IdProduct { get; set; }
        public int IdWareHouse { get; set; }
        public int Qty { get; set; }
    }
}
